[variables]
    NODE_ENV = "production"
    NODE_OPTIONS = "--max-old-space-size=3072"

[phases.setup]
    nixPkgs = ["nodejs_20", "python3", "pkg-config", "vips"]

[phases.build]
    cmds = ["npm run build"]

[start]
    cmd = "npm run preview"
