export const instructorStyles = {
  seccionInstructor: {
    position: 'relative' as const,
    padding: '8rem 0',
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #374151 100%)',
    color: 'white',
    overflow: 'hidden',
  },
  fondoAtmosferico: {
    position: 'absolute' as const,
    inset: '0',
    zIndex: 1,
  },
  patronMusical: {
    position: 'absolute' as const,
    inset: '0',
    backgroundImage: `
      radial-gradient(circle at 25% 25%, rgba(251, 191, 36, 0.1) 2px, transparent 2px),
      radial-gradient(circle at 75% 75%, rgba(124, 58, 237, 0.1) 2px, transparent 2px)
    `,
    backgroundSize: '60px 60px',
    animation: 'floatPattern 20s linear infinite',
  },
  gradienteOverlay: {
    position: 'absolute' as const,
    inset: '0',
    background: 'radial-gradient(ellipse at center, transparent 30%, rgba(15, 23, 42, 0.8) 100%)',
  },
  contenedor: {
    position: 'relative' as const,
    zIndex: 10,
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '0 2rem',
  },
  headerEmocional: {
    textAlign: 'center' as const,
    marginBottom: '6rem',
  },
  badgeQuestion: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '0.8rem 2rem',
    borderRadius: '50px',
    fontWeight: 700,
    fontSize: '0.9rem',
    marginBottom: '2rem',
    boxShadow: '0 8px 25px rgba(251, 191, 36, 0.3)',
    animation: 'pulseGlow 3s ease-in-out infinite',
  },
  tituloEmocional: {
    fontSize: 'clamp(2.5rem, 6vw, 5rem)',
    fontWeight: 900,
    lineHeight: 1.1,
    margin: 0,
  },
  preguntaClave: {
    display: 'block',
    color: '#e2e8f0',
    marginBottom: '0.5rem',
  },
  respuestaDorada: {
    display: 'block',
    background: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 50%, #d97706 100%)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  contenidoSplit: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.2fr',
    gap: '5rem',
    alignItems: 'center',
  },
  ladoIzquierdo: {},
  collageMaestro: {
    position: 'relative' as const,
    marginBottom: '3rem',
  },
  fotoPrincipal: {
    position: 'relative' as const,
    borderRadius: '20px',
    overflow: 'hidden',
    boxShadow: '0 25px 50px rgba(0, 0, 0, 0.3)',
  },
  imgMaestro: {
    width: '100%',
    height: 'auto',
    objectFit: 'contain' as const,
    transition: 'transform 0.3s ease',
    maxHeight: 'none',
  },
  overlayProfesional: {
    position: 'absolute' as const,
    inset: '0',
    background: 'linear-gradient(135deg, rgba(251, 191, 36, 0.1) 0%, rgba(124, 58, 237, 0.1) 100%)',
  },
  badgeExperiencia: {
    position: 'absolute' as const,
    top: '20px',
    right: '20px',
    background: 'rgba(0, 0, 0, 0.8)',
    backdropFilter: 'blur(10px)',
    padding: '1rem',
    borderRadius: '15px',
    textAlign: 'center' as const,
    border: '2px solid rgba(251, 191, 36, 0.3)',
  },
  numeroAnos: {
    display: 'block',
    fontSize: '2rem',
    fontWeight: 900,
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  textoAnos: {
    display: 'block',
    fontSize: '0.8rem',
    fontWeight: 600,
    color: '#cbd5e1',
  },
  ladoDerecho: {},
  presentacionPersonal: {
    height: '100%',
  },
  saludoPersonal: {
    fontSize: 'clamp(2rem, 4vw, 3rem)',
    fontWeight: 800,
    color: '#fbbf24',
    marginBottom: '0.5rem',
    lineHeight: 1.2,
  },
  subtituloPersonal: {
    fontSize: '1.3rem',
    color: '#94a3b8',
    marginBottom: '3rem',
    fontWeight: 600,
  },
  historiaEmotiva: {
    marginBottom: '3rem',
  },
  parrafoPrincipal: {
    fontSize: '1.1rem',
    lineHeight: 1.8,
    color: '#e2e8f0',
    marginBottom: '1.5rem',
  },
  parrafoGarantia: {
    fontSize: '1.15rem',
    lineHeight: 1.8,
    color: '#e2e8f0',
    marginBottom: '1.5rem',
    background: 'rgba(251, 191, 36, 0.1)',
    padding: '1.5rem',
    borderRadius: '12px',
    borderLeft: '4px solid #fbbf24',
  },
  parrafoDiferencia: {
    fontSize: '1.1rem',
    lineHeight: 1.8,
    color: '#e2e8f0',
    marginBottom: '1.5rem',
  },
  parrafoUrgencia: {
    fontSize: '1.1rem',
    lineHeight: 1.8,
    color: '#e2e8f0',
    marginBottom: '2rem',
    textAlign: 'center' as const,
    background: 'rgba(220, 38, 38, 0.1)',
    padding: '1.5rem',
    borderRadius: '12px',
    border: '2px solid rgba(220, 38, 38, 0.3)',
  },
  ctaMaestro: {
    marginTop: '2rem',
  },
  ctaPrincipal: {
    width: '100%',
    padding: '2rem',
    borderRadius: '15px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 800,
    fontSize: '1.2rem',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    background: 'linear-gradient(135deg, #dc2626 0%, #b91c1c 50%, #991b1b 100%)',
    color: 'white',
    boxShadow: '0 15px 40px rgba(220, 38, 38, 0.4)',
  },
  ctaSubtitle: {
    fontSize: '0.9rem',
    fontWeight: 400,
    opacity: 0.95,
    textTransform: 'none' as const,
    letterSpacing: 'normal',
    marginTop: '0.5rem',
    lineHeight: 1.4,
  },
};
