export const opcionesStyles = {
  seccionOpciones: {
    padding: '5rem 0',
    background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #f1f5f9 100%)',
    position: 'relative' as const,
    overflow: 'hidden',
    scrollMarginTop: '100px',
  },
  contenedor: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '0 1rem',
    position: 'relative' as const,
    zIndex: 10,
  },
  headerSeccion: {
    textAlign: 'center' as const,
    marginBottom: '4rem',
  },
  badgeSeccion: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '0.75rem 2rem',
    borderRadius: '50px',
    fontWeight: 700,
    fontSize: '0.9rem',
    marginBottom: '1.5rem',
    boxShadow: '0 8px 25px rgba(251, 191, 36, 0.3)',
    animation: 'pulseGlow 3s ease-in-out infinite',
  },
  tituloSeccion: {
    fontSize: 'clamp(2rem, 5vw, 3.5rem)',
    fontWeight: 900,
    color: '#1e293b',
    lineHeight: 1.2,
    marginBottom: '1.5rem',
  },
  textoDestacado: {
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  textoPrincipal: {
    color: '#3b82f6',
  },
  descripcionSeccion: {
    fontSize: 'clamp(1rem, 2.5vw, 1.2rem)',
    color: '#64748b',
    lineHeight: 1.6,
    maxWidth: '800px',
    margin: '0 auto',
  },
  textoUrgencia: {
    color: '#dc2626',
    fontWeight: 700,
  },
  gridOpciones: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '2.5rem',
    marginBottom: '4rem',
    maxWidth: '1000px',
    margin: '0 auto 4rem auto',
  },
  tarjetaOpcion: {
    background: 'white',
    borderRadius: '20px',
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'all 0.4s ease',
    cursor: 'pointer',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.1)',
    border: '2px solid transparent',
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
  },
  destacada: {
    border: '2px solid #fbbf24',
    boxShadow: '0 15px 40px rgba(251, 191, 36, 0.2)',
    position: 'relative' as const,
    animation: 'brilloDestacado 3s ease-in-out infinite',
  },
  etiquetaDestacado: {
    position: 'absolute' as const,
    top: '1rem',
    right: '1rem',
    background: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    color: 'white',
    padding: '0.5rem 1rem',
    borderRadius: '20px',
    fontSize: '0.8rem',
    fontWeight: 700,
    zIndex: 20,
    boxShadow: '0 4px 15px rgba(220, 38, 38, 0.3)',
  },
  imagenContenedor: {
    position: 'relative' as const,
    height: '200px',
    overflow: 'hidden',
  },
  imagenOpcion: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    transition: 'transform 0.4s ease',
  },
  overlayImagen: {
    position: 'absolute' as const,
    inset: '0',
    background: 'linear-gradient(135deg, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.1) 100%)',
  },
  iconoOpcion: {
    position: 'absolute' as const,
    top: '1rem',
    left: '1rem',
    background: 'rgba(255, 255, 255, 0.9)',
    width: '50px',
    height: '50px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.1)',
  },
  brilloDestacado: {
    position: 'absolute' as const,
    inset: '0',
    background: 'linear-gradient(45deg, transparent, rgba(251, 191, 36, 0.3), transparent)',
    animation: 'brillo 2s ease-in-out infinite',
  },
  contenidoTarjeta: {
    padding: '2rem',
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
  },
  headerTarjeta: {
    marginBottom: '1.5rem',
    textAlign: 'center' as const,
  },
  tituloOpcion: {
    fontSize: '1.3rem',
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: '0.5rem',
  },
  descripcionOpcion: {
    color: '#64748b',
    fontSize: '0.95rem',
    lineHeight: 1.5,
    textAlign: 'center' as const,
  },
  beneficiosLista: {
    marginBottom: '2rem',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
  },
  beneficioItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '0.75rem',
    fontSize: '0.9rem',
    color: '#374151',
  },
  checkIcon: {
    background: 'linear-gradient(135deg, #10b981, #059669)',
    color: 'white',
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.7rem',
    fontWeight: 700,
    flexShrink: 0,
  },
  footerTarjeta: {
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    gap: '1.25rem',
    marginTop: 'auto',
  },
  precioOpcion: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#dc2626',
    textAlign: 'center' as const,
  },
  precioDestacado: {
    fontSize: '1.3rem',
    color: '#fbbf24',
    textShadow: '1px 1px 2px rgba(0, 0, 0, 0.1)',
  },
  botonExplorar: {
    padding: '0.75rem 1.5rem',
    border: 'none',
    borderRadius: '25px',
    color: 'white',
    fontWeight: 600,
    fontSize: '0.9rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    textDecoration: 'none',
    whiteSpace: 'nowrap' as const,
  },
  botonDestacado: {
    padding: '1rem 2rem',
    fontSize: '1rem',
    fontWeight: 700,
    animation: 'pulseButton 2s ease-in-out infinite',
  },
  flechaIcon: {
    transition: 'transform 0.3s ease',
  },
  efectoHover: {},
  ctaAdicional: {
    background: 'linear-gradient(135deg, #1e293b, #334155)',
    borderRadius: '30px',
    padding: '3rem 2rem',
    textAlign: 'center' as const,
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.1)',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  ctaContenido: {
    position: 'relative' as const,
    zIndex: 10,
  },
  ctaIcono: {
    fontSize: '3rem',
    marginBottom: '1rem',
  },
  botonAsesoria: {
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '1.2rem 2.5rem',
    border: 'none',
    borderRadius: '25px',
    fontWeight: 700,
    fontSize: '1.1rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginBottom: '1.5rem',
    boxShadow: '0 8px 25px rgba(251, 191, 36, 0.3)',
  },
  garantiaTexto: {
    color: '#94a3b8',
    fontSize: '0.9rem',
  },
};
