export const ctaFinalStyles = {
  seccionCtaFinal: {
    padding: '6rem 0',
    background: 'linear-gradient(135deg, #7c2d12 0%, #dc2626 25%, #b91c1c 50%, #991b1b 75%, #7c2d12 100%)',
    color: 'white',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  contenedor: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '0 2rem',
    position: 'relative' as const,
    zIndex: 2,
  },
  mensajePrincipal: {
    textAlign: 'center' as const,
    marginBottom: '4rem',
  },
  badgeUrgencia: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '0.8rem 2rem',
    borderRadius: '50px',
    fontWeight: 700,
    fontSize: '0.9rem',
    marginBottom: '2rem',
    boxShadow: '0 8px 25px rgba(251, 191, 36, 0.4)',
    animation: 'pulseGlow 2s ease-in-out infinite',
  },
  tituloCta: {
    fontSize: 'clamp(2.5rem, 6vw, 4.5rem)',
    fontWeight: 900,
    marginBottom: '1.5rem',
    lineHeight: 1.1,
  },
  textoImpacto: {
    display: 'block',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '0.5rem',
  },
  textoMotivacion: {
    display: 'block',
    color: '#fecaca',
  },
  descripcionCta: {
    fontSize: '1.3rem',
    color: '#fecaca',
    maxWidth: '600px',
    margin: '0 auto',
    lineHeight: 1.6,
  },
  beneficiosFinales: {
    marginBottom: '4rem',
  },
  tituloBeneficios: {
    textAlign: 'center' as const,
    fontSize: '1.8rem',
    fontWeight: 800,
    color: '#fbbf24',
    marginBottom: '2rem',
  },
  gridBeneficios: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1rem',
    maxWidth: '800px',
    margin: '0 auto',
  },
  beneficioFinal: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    background: 'rgba(255, 255, 255, 0.1)',
    padding: '1rem 1.5rem',
    borderRadius: '12px',
    fontWeight: 600,
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  },
  checkFinal: {
    fontSize: '1.2rem',
    flexShrink: 0,
  },
  accionPrincipal: {
    textAlign: 'center' as const,
    marginBottom: '4rem',
  },
  botonMegaCta: {
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    border: 'none',
    padding: '2rem 3rem',
    borderRadius: '20px',
    fontWeight: 900,
    fontSize: '1.4rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 15px 40px rgba(251, 191, 36, 0.4)',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    margin: '0 auto 1.5rem auto',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  iconoBoton: {
    fontSize: '2rem',
  },
  textoBoton: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  textoPrincipal: {
    fontSize: '1.4rem',
    lineHeight: 1,
  },
  textoSecundario: {
    fontSize: '1rem',
    opacity: 0.8,
    textTransform: 'none' as const,
    letterSpacing: 'normal',
  },
  botonSimulador: {
    background: 'transparent',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    color: 'white',
    padding: '1rem 2rem',
    borderRadius: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  garantiaFinal: {
    marginBottom: '4rem',
  },
  contenidoGarantia: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1.5rem',
    background: 'rgba(255, 255, 255, 0.1)',
    padding: '2rem',
    borderRadius: '16px',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    maxWidth: '600px',
    margin: '0 auto',
  },
  iconoGarantia: {
    fontSize: '3rem',
    flexShrink: 0,
  },
  textoGarantia: {},
  mensajeCierre: {
    textAlign: 'center' as const,
  },
  contenidoCierre: {},
  fraseMotivacional: {
    fontStyle: 'italic',
    fontSize: '1.1rem',
    color: '#fed7aa',
    position: 'relative' as const,
    padding: '1.5rem',
    background: 'rgba(0, 0, 0, 0.2)',
    borderRadius: '12px',
    maxWidth: '500px',
    margin: '0 auto',
  },
  comillas: {
    fontSize: '2rem',
    color: '#fbbf24',
    fontWeight: 900,
  },
  frase: {
    fontWeight: 600,
  },
};
