export const statsStyles = {
  seccionStats: {
    padding: '6rem 0',
    background: 'linear-gradient(135deg, #1e293b 0%, #334155 50%, #475569 100%)',
    color: 'white',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  contenedor: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 2rem',
    position: 'relative' as const,
    zIndex: 2,
  },
  header: {
    textAlign: 'center' as const,
    marginBottom: '4rem',
  },
  badgeProof: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '0.8rem 2rem',
    borderRadius: '50px',
    fontWeight: 700,
    fontSize: '0.9rem',
    marginBottom: '1.5rem',
    boxShadow: '0 8px 25px rgba(251, 191, 36, 0.4)',
    animation: 'pulseGlow 3s ease-in-out infinite',
  },
  titulo: {
    fontSize: 'clamp(2.5rem, 6vw, 4rem)',
    fontWeight: 900,
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '1.5rem',
    lineHeight: 1.1,
  },
  descripcion: {
    fontSize: '1.3rem',
    color: '#cbd5e1',
    maxWidth: '800px',
    margin: '0 auto',
    lineHeight: 1.6,
  },
  gridStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '2rem',
    marginBottom: '5rem',
  },
  statCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    backdropFilter: 'blur(10px)',
    borderRadius: '24px',
    padding: '2.5rem 2rem',
    textAlign: 'center' as const,
    border: '1px solid rgba(255, 255, 255, 0.1)',
    transition: 'all 0.4s ease',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  destacado: {
    background: 'rgba(251, 191, 36, 0.08)',
    border: '2px solid rgba(251, 191, 36, 0.3)',
    transform: 'scale(1.02)',
  },
  icono: {
    fontSize: '3.5rem',
    marginBottom: '1rem',
    filter: 'drop-shadow(0 4px 8px rgba(0,0,0,0.3))',
  },
  numero: {
    fontSize: '4rem',
    fontWeight: 900,
    color: '#fbbf24',
    marginBottom: '0.5rem',
    lineHeight: 1,
    textShadow: '0 4px 8px rgba(0,0,0,0.3)',
  },
  sufijo: {
    fontSize: '2.5rem',
    opacity: 0.8,
  },
  tituloStat: {
    fontSize: '1.2rem',
    fontWeight: 700,
    color: '#e2e8f0',
    marginBottom: '1.5rem',
  },
  testimonioSutil: {
    background: 'rgba(0, 0, 0, 0.2)',
    borderRadius: '12px',
    padding: '1rem',
    marginTop: '1rem',
    borderLeft: '3px solid #fbbf24',
    position: 'relative' as const,
  },
  comillasMini: {
    position: 'absolute' as const,
    top: '-0.5rem',
    left: '0.5rem',
    fontSize: '2rem',
    color: '#fbbf24',
    fontWeight: 900,
  },
  textoTestimonio: {
    fontSize: '0.85rem',
    color: '#cbd5e1',
    fontStyle: 'italic',
    lineHeight: 1.4,
    margin: 0,
    paddingLeft: '1rem',
  },
  badgeDestacado: {
    position: 'absolute' as const,
    top: '1rem',
    right: '1rem',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '0.4rem 0.8rem',
    borderRadius: '20px',
    fontSize: '0.7rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  logrosComprobados: {
    marginBottom: '4rem',
  },
  tituloLogros: {
    textAlign: 'center' as const,
    fontSize: '2.2rem',
    fontWeight: 800,
    color: '#fbbf24',
    marginBottom: '3rem',
  },
  gridLogros: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '2rem',
  },
  logroCard: {
    background: 'rgba(255, 255, 255, 0.03)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '16px',
    padding: '2rem 1.5rem',
    textAlign: 'center' as const,
    transition: 'all 0.3s ease',
  },
  valorLogro: {
    fontSize: '2.5rem',
    fontWeight: 900,
    color: '#fbbf24',
    marginBottom: '0.5rem',
  },
  tituloLogro: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#e2e8f0',
    marginBottom: '0.8rem',
  },
  descripcionLogro: {
    fontSize: '0.9rem',
    color: '#94a3b8',
    lineHeight: 1.4,
  },
  mensajeVendedor: {
    background: 'linear-gradient(135deg, rgba(251, 191, 36, 0.1), rgba(245, 158, 11, 0.1))',
    border: '2px solid rgba(251, 191, 36, 0.3)',
    borderRadius: '20px',
    padding: '3rem 2rem',
    textAlign: 'center' as const,
    position: 'relative' as const,
    overflow: 'hidden',
  },
  contenidoVendedor: {
    position: 'relative' as const,
    zIndex: 2,
  },
  fraseImpacto: {
    fontSize: '1.3rem',
    fontWeight: 600,
    color: '#fbbf24',
    fontStyle: 'italic',
    background: 'rgba(0, 0, 0, 0.3)',
    padding: '1.5rem',
    borderRadius: '12px',
    borderLeft: '4px solid #fbbf24',
  },
};
