export const articuloStyles = {
  barraProgresoLectura: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    height: '4px',
    background: 'linear-gradient(90deg, #ff6b35, #ffd700)',
    zIndex: 9999,
    transition: 'width 0.2s ease',
  },
  paginaArticuloBlog: {
    width: '100%',
    maxWidth: '1600px',
    margin: '0 auto',
    padding: '2rem 1rem',
    transition: 'opacity 0.5s ease-out',
    marginTop: '50px',
  },
  contenedorArticulo: {
    maxWidth: '1500px',
    margin: '0 auto',
    padding: 0,
    position: 'relative' as const,
    zIndex: 2,
  },
  layoutArticulo: {
    display: 'grid',
    gridTemplateColumns: '1fr 320px',
    gap: '3rem',
    alignItems: 'flex-start',
  },
  contenidoPrincipal: { minWidth: 0 },
  contenidoArticuloBlog: {
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '24px',
    boxShadow: '0 8px 32px rgba(255, 107, 53, 0.15)',
    padding: '2.5rem',
    marginTop: '1.5rem',
    fontSize: '1.1rem',
    color: '#2c3e50',
    lineHeight: 1.8,
    wordBreak: 'break-word' as const,
    overflowWrap: 'anywhere' as const,
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    scrollMarginTop: '100px',
  },
  ctaFinalArticulo: {
    background: 'linear-gradient(135deg, #ff6b35, #f7931e)',
    borderRadius: '24px',
    padding: '3rem 2rem',
    marginTop: '3rem',
    textAlign: 'center' as const,
    color: 'white',
    boxShadow: '0 8px 32px rgba(255, 107, 53, 0.15)',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  ctaContenido: { position: 'relative' as const, zIndex: 2 },
  botonesCtaContainer: { display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' as const },
  botonCtaPrincipal: {
    padding: '1rem 2rem',
    borderRadius: '50px',
    textDecoration: 'none',
    fontWeight: 700,
    fontSize: '1.1rem',
    transition: 'all 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    border: '2px solid transparent',
    background: '#ffd700',
    color: '#2d5a3d',
    boxShadow: '0 8px 25px rgba(255, 215, 0, 0.3)',
  },
  botonCtaSecundario: {
    padding: '1rem 2rem',
    borderRadius: '50px',
    textDecoration: 'none',
    fontWeight: 700,
    fontSize: '1.1rem',
    transition: 'all 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    border: '2px solid white',
    background: 'transparent',
    color: 'white',
  },
  estadoCarga: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    minHeight: '60vh',
    padding: '3rem 2rem',
  },
  spinnerVallenato: { position: 'relative' as const, marginBottom: '2rem' },
  acordeonAnimado: { fontSize: '4rem', animation: 'tocarAcordeon 1.5s ease-in-out infinite' },
  estadoError: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    minHeight: '60vh',
    padding: '3rem 2rem',
    background: 'rgba(255, 107, 53, 0.05)',
    borderRadius: '24px',
    border: '2px solid rgba(255, 107, 53, 0.2)',
  },
  iconoError: { fontSize: '4rem', marginBottom: '1rem' },
  botonVolver: {
    background: 'linear-gradient(135deg, #ff6b35, #f7931e)',
    color: 'white',
    border: 'none',
    borderRadius: '50px',
    padding: '1rem 2rem',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 8px 32px rgba(255, 107, 53, 0.15)',
  },
};
