export const blogStyles = {
  paginaBlog: {
    width: '100%',
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
  },
  seccionArticulos: {
    padding: '4rem 1.5rem',
    maxWidth: '1800px',
    width: '95%',
    margin: '0 auto',
    transition: 'all 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  estadoCarga: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    minHeight: '400px',
    padding: '3rem 2rem',
  },
  spinnerCarga: {
    width: '50px',
    height: '50px',
    border: '4px solid #e2e8f0',
    borderTop: '4px solid #3b82f6',
    borderRadius: '50%',
    animation: 'girar 1s linear infinite',
    marginBottom: '1.5rem',
  },
  estadoError: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    minHeight: '400px',
    padding: '3rem 2rem',
    background: 'rgba(239, 68, 68, 0.05)',
    borderRadius: '20px',
    border: '1px solid rgba(239, 68, 68, 0.1)',
  },
  iconoError: { fontSize: '3rem', marginBottom: '1rem' },
  botonReintentar: {
    background: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    padding: '0.8rem 2rem',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(220, 38, 38, 0.3)',
  },
  encabezadoSeccion: { textAlign: 'center' as const, marginBottom: '3rem' },
  contenidoPrincipal: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 340px',
    gap: '3rem',
    alignItems: 'start',
  },
  areaArticulos: { width: '100%' },
  grillaArticulos: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '2rem',
  },
  envolturioArticulo: {
    opacity: 0,
    transform: 'translateY(30px)',
    animation: 'aparecerArriba 0.6s forwards ease-out',
  },
  estadoVacio: {
    gridColumn: '1 / -1',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    minHeight: '400px',
    padding: '3rem 2rem',
    background: 'rgba(59, 130, 246, 0.05)',
    borderRadius: '20px',
    border: '1px solid rgba(59, 130, 246, 0.1)',
  },
  paginacion: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '1rem',
    marginTop: '3rem',
    padding: '2rem 0',
  },
  botonPagina: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    background: 'linear-gradient(135deg, #3b82f6, #1e40af)',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    padding: '0.8rem 1.5rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.3)',
  },
  botonDeshabilitado: { background: '#e2e8f0', color: '#94a3b8', cursor: 'not-allowed', boxShadow: 'none' },
  numerosPagina: { display: 'flex', gap: '0.5rem' },
  numeroPagina: {
    width: '40px',
    height: '40px',
    border: '1px solid #e2e8f0',
    background: 'white',
    color: '#64748b',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontWeight: 600,
  },
  numeroPaginaActiva: {
    background: 'linear-gradient(135deg, #3b82f6, #1e40af)',
    color: 'white',
    borderColor: 'transparent',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.3)',
  },
  barraLateral: { position: 'relative' as const },
};
