export function getModalInicioSesionStyles(isMobile: boolean) {
  return {
    fondoModal: {
      position: 'fixed' as const,
      top: 0, left: 0,
      width: '100vw', height: '100vh',
      background: 'rgba(0, 0, 0, 0.6)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: isMobile ? 'flex-start' : 'center',
      justifyContent: 'center',
      zIndex: 9999,
      opacity: 1,
      animation: 'fadeIn 0.3s ease-out forwards',
      padding: isMobile ? '16px' : '16px',
      paddingTop: isMobile ? '40px' : '16px',
      overflowY: 'auto' as const,
    },
    modalInicioSesion: {
      width: '100%', maxWidth: '420px',
      background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)',
      borderRadius: isMobile ? '20px' : '24px',
      boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      padding: 0,
      position: 'relative' as const,
      display: 'flex', flexDirection: 'column' as const,
      transform: 'translateY(0)',
      animation: 'slideInUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) 0.1s forwards',
      overflow: 'hidden',
      border: '1px solid rgba(255, 255, 255, 0.2)',
      marginBottom: isMobile ? '40px' : 'auto',
    },
    modalHeader: {
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      padding: isMobile ? '12px 16px' : '16px 24px 12px',
      borderBottom: '1px solid rgba(226, 232, 240, 0.3)',
      background: 'linear-gradient(135deg, rgba(255, 102, 0, 0.03) 0%, rgba(255, 102, 0, 0.08) 100%)',
    },
    logoContainer: { display: 'flex', alignItems: 'center', gap: '12px' },
    logoModal: {
      width: isMobile ? '40px' : '56px', height: isMobile ? '40px' : '56px',
      borderRadius: '50%', boxShadow: '0 4px 12px rgba(255, 102, 0, 0.2)',
      transition: 'transform 0.3s ease', objectFit: 'contain' as const,
    },
    botonCerrar: {
      width: isMobile ? '36px' : '40px', height: isMobile ? '36px' : '40px',
      borderRadius: '50%', border: 'none',
      background: 'rgba(255, 102, 0, 0.1)', color: '#ff6600',
      cursor: 'pointer', transition: 'all 0.3s ease',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    },
    tituloModal: {
      fontSize: isMobile ? '1.5rem' : '1.875rem', fontWeight: 800,
      background: 'linear-gradient(135deg, #ff6600 0%, #ff8c42 100%)',
      WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text',
      margin: isMobile ? '12px 16px 4px' : '16px 24px 6px',
      textAlign: 'center' as const, lineHeight: 1.2,
    },
    loginDesc: {
      color: '#64748b', fontSize: isMobile ? '0.9rem' : '1rem',
      margin: isMobile ? '0 16px 16px' : '0 24px 20px',
      textAlign: 'center' as const, lineHeight: 1.4,
    },
    formularioInicioSesion: {
      display: 'flex', flexDirection: 'column' as const,
      gap: isMobile ? '12px' : '16px',
      padding: isMobile ? '0 16px 16px' : '0 24px 20px',
    },
    campoFormulario: { display: 'flex', flexDirection: 'column' as const, gap: '8px', margin: 0, padding: 0 },
    label: { fontSize: '0.875rem', color: '#1e293b', fontWeight: 600, margin: 0, padding: 0 },
    inputIcono: {
      position: 'relative' as const, display: 'flex', alignItems: 'center',
      background: '#f8fafc', border: '2px solid #e2e8f0', borderRadius: '12px',
      padding: 0, transition: 'all 0.3s ease', overflow: 'hidden',
    },
    input: {
      flex: 1, border: 'none', background: 'transparent',
      padding: isMobile ? '10px 14px' : '12px 16px',
      fontSize: '1rem', color: '#1e293b', outline: 'none',
      minHeight: isMobile ? '42px' : '48px',
    },
    iconoInput: { padding: isMobile ? '0 12px' : '0 16px', fontSize: '1.25rem', color: '#ff6600' },
    botonMostrarContrasena: {
      background: 'none', border: 'none', padding: '12px', cursor: 'pointer',
      fontSize: '1.25rem', color: '#64748b', transition: 'color 0.3s ease',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    },
    botonEnviar: {
      background: 'linear-gradient(135deg, #ff6600 0%, #ff8c42 100%)',
      color: 'white', border: 'none', borderRadius: '12px',
      padding: isMobile ? '14px 20px' : '16px 24px',
      fontSize: '1rem', fontWeight: 600, cursor: 'pointer',
      transition: 'all 0.3s ease', marginTop: '4px',
      boxShadow: '0 4px 12px rgba(255, 102, 0, 0.3)',
      position: 'relative' as const, overflow: 'hidden',
      minHeight: isMobile ? '48px' : '52px',
    },
    mensajeError: {
      background: '#fef2f2', color: '#dc2626',
      border: '1px solid rgba(220, 38, 38, 0.2)', borderRadius: '8px',
      padding: '12px 16px', fontSize: '0.875rem',
      textAlign: 'center' as const, margin: '-8px 0 8px',
    },
    mensajeRecuperar: {
      border: '1px solid rgba(99, 102, 241, 0.2)', borderRadius: '8px',
      padding: '12px 16px', fontSize: '0.875rem', margin: '-8px 0 8px',
      lineHeight: 1.4, background: '#f0fdf4', color: '#16a34a', textAlign: 'center' as const,
    },
    separadorO: {
      display: 'flex', alignItems: 'center', gap: '16px',
      margin: isMobile ? '12px 16px 12px' : '16px 24px 12px',
    },
    linea: { flex: 1, height: '1px', background: 'linear-gradient(90deg, transparent 0%, #e2e8f0 50%, transparent 100%)' },
    textoO: { fontSize: '0.875rem', color: '#64748b', fontWeight: 500, whiteSpace: 'nowrap' as const },
    botonesSociales: {
      padding: isMobile ? '0 16px 8px' : '0 24px 8px',
      display: 'flex', flexDirection: isMobile ? 'column' as const : 'row' as const,
      gap: '12px', width: '100%', boxSizing: 'border-box' as const,
    },
    botonGoogle: {
      flex: 1, background: 'white', border: '2px solid #e2e8f0', borderRadius: '12px',
      padding: isMobile ? '12px 12px' : '14px 16px',
      display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px',
      cursor: 'pointer', transition: 'all 0.3s ease',
      fontSize: isMobile ? '0.85rem' : '0.9rem', fontWeight: 600, color: '#1e293b',
      position: 'relative' as const, overflow: 'hidden',
    },
    botonFacebook: {
      flex: 1, background: '#1877F2', border: 'none', borderRadius: '12px',
      padding: isMobile ? '12px 12px' : '14px 16px',
      display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px',
      cursor: 'pointer', transition: 'all 0.3s ease',
      fontSize: isMobile ? '0.85rem' : '0.9rem', fontWeight: 600, color: 'white',
      position: 'relative' as const, overflow: 'hidden',
    },
    enlacesExtra: {
      padding: isMobile ? '0 16px 16px' : '0 24px 16px',
      display: 'flex', flexDirection: 'column' as const, gap: '8px', alignItems: 'center',
      borderTop: '1px solid rgba(226, 232, 240, 0.3)', marginTop: '4px', paddingTop: '12px',
    },
    enlaceOlvido: {
      background: 'none', border: 'none', color: '#1a73e8',
      fontSize: '0.875rem', cursor: 'pointer', transition: 'all 0.3s ease',
      padding: '8px 16px', borderRadius: '8px', fontFamily: 'inherit', textDecoration: 'none',
    },
    filaNombreApellido: {
      display: 'grid', gridTemplateColumns: '1fr 1fr',
      gap: isMobile ? '12px' : '20px', width: '100%', boxSizing: 'border-box' as const,
    },
    inputWhatsapp: {
      display: 'flex', background: '#f8fafc', border: '2px solid #e2e8f0',
      borderRadius: '12px', overflow: 'hidden', transition: 'all 0.3s ease', width: '100%', gap: 0,
    },
    selectorPaisContainer: {
      position: 'relative' as const, display: 'flex', alignItems: 'center',
      minWidth: isMobile ? '80px' : '90px',
    },
    selectorPais: {
      background: 'rgba(255, 102, 0, 0.05)', border: 'none',
      padding: '6px 4px', paddingRight: '20px', fontSize: '0.875rem',
      color: '#1e293b', cursor: 'pointer', outline: 'none', width: '100%',
      borderRight: '1px solid #e2e8f0', appearance: 'none' as const,
    },
    flechaSelector: {
      position: 'absolute' as const, right: '4px', top: '50%', transform: 'translateY(-50%)',
      color: '#64748b', fontSize: '10px', pointerEvents: 'none' as const, zIndex: 1,
    },
    inputNumero: { flex: 1, display: 'flex', alignItems: 'center' },
  }
}
